### ISSUE TITLE
Consider provide user interaction callbacks (ex: onclick)

### ISSUE THREAD

**Issue by TuSKan** [rstudio/r2d3#22]
Examples : mouseover, mouseout, onclick, mousemove

**Comment by jjallaire** [comment]
@javierluraschi Is there anything special we would do here? It seems like this is already covered by the D3 API (i.e. you can provide these callbacks directly without any help from r2d3) but perhaps I'm missing something.

**Comment by jjallaire** [comment]
One thing we aren't trying to do in the basic examples is teach D3 (as that's a much, much bigger topic!). That's why we created the Learning D3 page: https://rstudio.github.io/r2d3/articles/learning_d3.html

So I could add the simple interactions suggested here, but that will also just beg the question of how to do other non-toy interactions.
